import AboutUs from './AboutUs/AboutUs';
import Findus from './Findus/Findus';
import Footer from './Footer/Footer';
import Gallery from './Gallery/Gallery';
import Header from './Header/Header';
import Intro from './Intro/Intro';
import Menu from './Menu/Menu';
import Laurels from './Laurels/Laurels';
import Chef from './Chef/Chef';
import Login from './Login/Login';
export { AboutUs, Findus, Footer, Gallery, Header, Intro, Menu, Laurels, Chef, Login };